### ISSUE TITLE
redirect logs to standard output

### ISSUE THREAD

**Issue by Edzilla2000** [jacobalberty/cups-docker#3]
Currently logs are sent to a docker volume in /config/log
Would it be possible to redirect it to stdout so it could be picked up by docker?

**Comment by Edzilla2000** [comment]
Changing cups-files.conf to have those three lines sends all log to the docker container logs:
`AccessLog stderr`
`ErrorLog stderr`
`PageLog stderr`

**Comment by jacobalberty** [comment]
I'm working up a patch now so that by default it will change cups-files.conf to  update those error log locations. It will only take effect on first run if /config/etc/ doesn't exist yet and passing the environment variable LOGSTDERR with the value false will cause it to fall back to the original behavior
